# Generated by Django 5.0.1 on 2024-01-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0008_addday_addhours'),
        ('secondary', '0008_addchat_alter_addstudent_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Выберите дату старта')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_day', to='secondary.addadmin', verbose_name='Выберите куратора')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_day', to='base.addday', verbose_name='Выберите дневной график')),
                ('devop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_devip', to='base.adddevop', verbose_name='Выберите направление группы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_group', to='secondary.addchat', verbose_name='Выберите группу в которую хотите отправить рассылку')),
                ('hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_day', to='base.addhours', verbose_name='Выберите часовой график')),
                ('mounth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_mounth', to='base.addmounthteach', verbose_name='Выберите месяц группы')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_day', to='secondary.addteacher', verbose_name='Выберите преподователя')),
            ],
            options={
                'verbose_name': '1) Отправить рассылку  старте',
                'verbose_name_plural': '1) Отправить рассылку  старте',
            },
        ),
    ]
