# Generated by Django 5.0.1 on 2024-01-23 16:39

import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0008_addday_addhours'),
        ('secondary', '0011_alter_addchat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Включить/Отключить')),
                ('days', models.DateField(verbose_name='Выберите день ')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Выберите время')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_group_mailing', to='secondary.addchat', verbose_name='Выберите группу')),
            ],
            options={
                'verbose_name': '3) Настроить дневную рассылку',
                'verbose_name_plural': '3) Настроить дневную рассылку',
            },
        ),
        migrations.CreateModel(
            name='MailingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to_all', models.BooleanField(default=False, verbose_name='Отправить всем группам')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='team_image/', verbose_name='Фотография')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание 2')),
                ('group', models.ManyToManyField(blank=True, related_name='mailing_group', to='secondary.addchat', verbose_name='Выберите группу в которую хотите отправить рассылку')),
            ],
            options={
                'verbose_name': '2) Отправить рассылку  всем',
                'verbose_name_plural': '2) Отправить рассылку  всем',
            },
        ),
        migrations.CreateModel(
            name='StartMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Выберите дату старта')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_day', to='secondary.addadmin', verbose_name='Выберите куратора')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_day', to='base.addday', verbose_name='Выберите дневной график')),
                ('devop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_devip', to='base.adddevop', verbose_name='Выберите направление группы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_group', to='secondary.addchat', verbose_name='Выберите группу в которую хотите отправить рассылку')),
                ('hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_day', to='base.addhours', verbose_name='Выберите часовой график')),
                ('mounth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_mounth', to='base.addmounthteach', verbose_name='Выберите месяц группы')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_day', to='secondary.addteacher', verbose_name='Выберите преподователя')),
            ],
            options={
                'verbose_name': '1) Отправить рассылку  старте',
                'verbose_name_plural': '1) Отправить рассылку  старте',
            },
        ),
    ]
