# Generated by Django 5.0.1 on 2024-01-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymailing',
            name='lesson_time',
            field=models.DateField(blank=True, null=True, verbose_name='Укажите время урока'),
        ),
    ]
