# Generated by Django 5.0.1 on 2024-01-18 08:31

import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('secondary', '0008_addchat_alter_addstudent_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='team_image/', verbose_name='Фотография')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание 2')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_group', to='secondary.addchat', verbose_name='Выберите группу в которую хотите отправить рассылку')),
            ],
            options={
                'verbose_name': '1) Отправить рассылку  всем',
                'verbose_name_plural': '1) Отправить рассылку  всем',
            },
        ),
    ]
