# Generated by Django 5.0.1 on 2024-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_daymailing_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymailing',
            name='days',
            field=models.DateField(blank=True, null=True, verbose_name='Выберите день'),
        ),
        migrations.AlterField(
            model_name='daymailing',
            name='lesson_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время урока'),
        ),
    ]
