# Generated by Django 5.0.1 on 2024-01-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_mailinggroup_group_mailinggroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinggroup',
            name='send_to_all',
            field=models.BooleanField(default=False, verbose_name='Отправить всем группам'),
        ),
    ]
