# Generated by Django 5.0.1 on 2024-01-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_addday_addhours'),
        ('contacts', '0004_alter_daymailing_days_alter_daymailing_lesson_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daymailing',
            name='days',
        ),
        migrations.AddField(
            model_name='daymailing',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='day_mailing_days', to='base.addday', verbose_name='Выберите дни'),
        ),
    ]
