# Generated by Django 5.0.1 on 2024-01-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_mailinggroup_group'),
        ('secondary', '0008_addchat_alter_addstudent_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinggroup',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='mailing_group', to='secondary.addchat', verbose_name='Выберите группу в которую хотите отправить рассылку'),
        ),
    ]
