# Generated by Django 5.0.1 on 2024-01-23 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_daymailing_days_daymailing_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daymailing',
            name='days',
        ),
        migrations.CreateModel(
            name='DayAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateField(blank=True, null=True, verbose_name='Выберите день')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_mailing', to='contacts.daymailing', verbose_name='Добавьте дни')),
            ],
        ),
    ]
