# Generated by Django 5.0.1 on 2024-01-16 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_alter_addchat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='Введите id студента')),
                ('name', models.CharField(max_length=255, verbose_name='Введите ФИО студента')),
                ('age', models.DateField(auto_now_add=True, verbose_name='Дата рождения')),
                ('usrname', models.CharField(blank=True, max_length=255, null=True, verbose_name='username Студента')),
                ('devop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_devop', to='base.adddevop', verbose_name='Выберите Направление')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='base.addchat', verbose_name='Выберите группу')),
            ],
            options={
                'verbose_name': '1) Добавить Студента',
                'verbose_name_plural': '1) Добавить Студента',
            },
        ),
    ]
