# Generated by Django 5.0.1 on 2024-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='age',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
