# Generated by Django 5.0.1 on 2024-01-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_alter_addstudent_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudent',
            name='devop',
        ),
    ]
