# Generated by Django 5.0.1 on 2024-01-18 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_addchat_options_alter_addmounthteach_options'),
        ('secondary', '0003_remove_addstudent_devop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addstudent',
            options={'verbose_name': '1) Добавить студента', 'verbose_name_plural': '1) Добавить студента'},
        ),
        migrations.CreateModel(
            name='AddAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='Введите id администратора')),
                ('name', models.CharField(max_length=255, verbose_name='Введите ФИО администратора')),
                ('age', models.DateField(verbose_name='Дата рождения')),
                ('usrname', models.CharField(blank=True, max_length=255, null=True, verbose_name='username администратора')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_group', to='base.addchat', verbose_name='Выберите группу')),
            ],
            options={
                'verbose_name': '3) Добавить администратора',
                'verbose_name_plural': '3) Добавить администратора',
            },
        ),
        migrations.CreateModel(
            name='AddTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='Введите id учителя')),
                ('name', models.CharField(max_length=255, verbose_name='Введите ФИО учителя')),
                ('age', models.DateField(verbose_name='Дата рождения')),
                ('usrname', models.CharField(blank=True, max_length=255, null=True, verbose_name='username учителя')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_group', to='base.addchat', verbose_name='Выберите группу')),
            ],
            options={
                'verbose_name': '2) Добавить учителя',
                'verbose_name_plural': '2) Добавить учителя',
            },
        ),
    ]
