# Generated by Django 5.0.1 on 2024-01-18 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_addchat_options_alter_addmounthteach_options'),
        ('secondary', '0005_remove_addadmin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='addadmin',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_group', to='base.addchat', verbose_name='Выберите группу'),
            preserve_default=False,
        ),
    ]
