# Generated by Django 5.0.1 on 2024-01-18 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_addadmin_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addadmin',
            name='group',
        ),
    ]
