# Generated by Django 5.0.1 on 2024-01-18 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_addchat_devop_remove_addchat_mounth'),
        ('secondary', '0007_remove_addadmin_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название чата/группы')),
                ('chat_id', models.CharField(max_length=255, verbose_name='Id чата')),
                ('devop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_devop', to='base.adddevop')),
                ('mounth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='give_devop', to='base.addmounthteach')),
            ],
            options={
                'verbose_name': '3) Добавить группу',
                'verbose_name_plural': '3) Добавить группу',
            },
        ),
        migrations.AlterField(
            model_name='addstudent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='secondary.addchat', verbose_name='Выберите группу'),
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_group', to='secondary.addchat', verbose_name='Выберите группу'),
        ),
    ]
