# Generated by Django 5.0.1 on 2024-01-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_addchat_alter_addstudent_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addchat',
            options={'verbose_name': '1) Добавить группу', 'verbose_name_plural': '1) Добавить группу'},
        ),
        migrations.AlterModelOptions(
            name='addstudent',
            options={'verbose_name': '4) Добавить студента', 'verbose_name_plural': '4) Добавить студента'},
        ),
    ]
