# Generated by Django 5.0.1 on 2024-01-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_alter_addchat_options_alter_addstudent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addchat',
            options={'verbose_name': '3) Добавить группу', 'verbose_name_plural': '3) Добавить группу'},
        ),
    ]
