# Generated by Django 5.0.1 on 2024-01-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_alter_addchat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addchat',
            options={'verbose_name': '1) Добавить группу', 'verbose_name_plural': '1) Добавить группу'},
        ),
    ]
