# Generated by Django 5.0.1 on 2024-01-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, verbose_name='Id чата')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название чата/группы')),
            ],
            options={
                'verbose_name': '1) Добавить направление',
                'verbose_name_plural': '1) Добавить направление',
            },
        ),
        migrations.CreateModel(
            name='AddDevop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Введите название направления')),
            ],
            options={
                'verbose_name': '1) Добавить направление',
                'verbose_name_plural': '1) Добавить направление',
            },
        ),
    ]
