# Generated by Django 5.0.1 on 2024-01-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addchat',
            name='devop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='give_devop', to='base.adddevop'),
            preserve_default=False,
        ),
    ]
