# Generated by Django 5.0.1 on 2024-01-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_addchat_devop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addchat',
            options={'verbose_name': '2) Добавить группу', 'verbose_name_plural': '2) Добавить группу'},
        ),
    ]
