# Generated by Django 5.0.1 on 2024-01-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_addchat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMounthTeach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Введите название месяца')),
            ],
            options={
                'verbose_name': '1) Добавить месяц',
                'verbose_name_plural': '1) Добавить месяц',
            },
        ),
        migrations.AddField(
            model_name='addchat',
            name='mounth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='give_devop', to='base.addmounthteach'),
        ),
    ]
