# Generated by Django 5.0.1 on 2024-01-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_addmounthteach_addchat_mounth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addchat',
            options={'verbose_name': '3) Добавить группу', 'verbose_name_plural': '3) Добавить группу'},
        ),
        migrations.AlterModelOptions(
            name='addmounthteach',
            options={'verbose_name': '2) Добавить месяц', 'verbose_name_plural': '2) Добавить месяц'},
        ),
    ]
