# Generated by Django 5.0.1 on 2024-01-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_addchat_options_alter_addmounthteach_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addchat',
            name='devop',
        ),
        migrations.RemoveField(
            model_name='addchat',
            name='mounth',
        ),
    ]
