# Generated by Django 5.0.1 on 2024-01-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_addchat_devop_remove_addchat_mounth'),
        ('secondary', '0008_addchat_alter_addstudent_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddChat',
        ),
    ]
