# Generated by Django 5.0.1 on 2024-01-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_addchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255, verbose_name='Введите график дней')),
            ],
            options={
                'verbose_name': '3) Добавить график дней',
                'verbose_name_plural': '3) Добавить график дней',
            },
        ),
        migrations.CreateModel(
            name='AddHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Введите график часов')),
            ],
            options={
                'verbose_name': '4) Добавить график часов',
                'verbose_name_plural': '4) Добавить график часов',
            },
        ),
    ]
